config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :coffees
  resources :authors
  root "wallets#index"
  get 'networks_config', to: 'application#networks_config'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/coffee.rb
class Coffee < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :load_networks

    # private

    def load_networks
        file_path = Rails.root.join('app', 'javascript', 'config', 'networks.json')
        @networks = JSON.parse(File.read(file_path))
    end
    
    def networks_config
        render json: @networks
    end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :bio, :wallet_address, :balance)
    end
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :set_coffee, only: %i[ show edit update destroy ]

  # GET /coffees or /coffees.json
  def index
    @coffees = Coffee.all
  end

  # GET /coffees/1 or /coffees/1.json
  def show
  end

  # GET /coffees/new
  def new
    @coffee = Coffee.new
  end

  # GET /coffees/1/edit
  def edit
  end

  # POST /coffees or /coffees.json
  def create
    @coffee = Coffee.new(coffee_params)
    # create a contract_id like rails does for id

    respond_to do |format|
      if @coffee.save
        format.html { redirect_to coffee_url(@coffee), notice: "Coffee was successfully created." }
        format.json { render :show, status: :created, location: @coffee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffees/1 or /coffees/1.json
  def update
    respond_to do |format|
      if @coffee.update(coffee_params)
        format.html { redirect_to coffee_url(@coffee), notice: "Coffee was successfully updated." }
        format.json { render :show, status: :ok, location: @coffee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffees/1 or /coffees/1.json
  def destroy
    @coffee.destroy

    respond_to do |format|
      format.html { redirect_to coffees_url, notice: "Coffee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee
      @coffee = Coffee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_params
      params.require(:coffee).permit(:profile_id, :sender_wallet_address, :name, :amount, :contract_id, :message, :tx_hash)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :slug, :bio, :wallet_address)
    end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
    def index
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= author.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Bio:</strong>
    <%= author.bio %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Wallet address:</strong>
    <%= author.wallet_address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Balance:</strong>
    <%= author.balance %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this author", author, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this author', edit_author_path(author), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, class: "contents") do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bio %>
    <%= form.text_area :bio, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :wallet_address %>
    <%= form.text_field :wallet_address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :balance %>
    <%= form.text_field :balance, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing author</h1>

  <%= render "form", author: @author %>

  <%= link_to "Show this author", @author, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to authors", authors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/authors/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Authors</h1>
    <%= link_to 'New author', new_author_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="authors" class="min-w-full">
    <%= render @authors %>
  </div>
</div>

app/views/authors/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New author</h1>

  <%= render "form", author: @author %>

  <%= link_to 'Back to authors', authors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/authors/show.html.erb
<!-- Notification -->
<%= render partial: "authors/wallet/notification" %>
<section class="mx-auto max-w-5xl px-8">
  <!-- CONTAINER -->
  <div class="flex items-start">
    <!-- LEFT SIDE -->
    <div class="w-1/2">
      <!-- Profile -->
      <%= render partial: "authors/wallet/profile" %>
      <!-- Transactions -->
      <%= render partial: "authors/wallet/transactions" %>
    </div>
    <!-- RIGHT SIDE -->
    <div class="w-1/2 h-screen sticky top-0 z-50 pl-2 grid justify-items-end">
      <!-- Form -->
      <%= render partial: "authors/wallet/form" %>
    </div>
  </div>
</section>

app/views/authors/wallet/_form.html.erb
<div class="w-full max-w-sm" x-data="{price: 0.001}">
  <div class="box-border border border-gray-200 shadow-md rounded px-8 py-6">
    <h1 class="font-semibold text-lg mb-4">
      Buy <span class="text-orange-500">Diogo Wernik</span> a coffee
    </h1>
    <!-- Button: Connect to Metamask -->
    <button 
      data-metamask-target="connect" 
      data-action="metamask#connectMetamask"
      hidden 
      class="mt-5 w-full rounded-md py-3 bg-black text-white font-semibold hover:scale-105 duration-300">
      <div class="flex items-center justify-center">
        Connect to <%= image_tag "metamask.png", class: "ml-2 h-6 w-6" %>
      </div>
    </button>
    <!-- Form: Buymeacoffee -->
    <div 
    hidden 
    data-metamask-target="form">
      <!-- Tabs: Coffee -->
      <div class="w-full flex items-center justify-evenly space-x-2 rounded-md border border-orange-200 bg-orange-500/10 px-2 py-5 mb-5">
        <span class="text-4xl">☕</span>
        <span class="text-gray-400 font-semibold">X</span>
        <div>
          <input type="radio" name="option" id="opt1" class="peer hidden" checked />
          <label @click="price=0.001" for="opt1" class="coffee-choice">1</label>
        </div>
        <div>
          <input type="radio" name="option" id="opt2" class="peer hidden" />
          <label @click="price=0.003" for="opt2" class="coffee-choice">3</label>
        </div>
        <div>
          <input type="radio" name="option" id="opt3" class="peer hidden" />
          <label @click="price=0.005" for="opt3" class="coffee-choice">5</label>
        </div>
      </div>
      <!-- Input: profileAdress = @author.wallet_address -->
      <input 
        data-metamask-target="profileAddress"
        type="hidden"   
        name="profileAddress" 
        value="<%= @author.wallet_address %>"
      >
      <!-- Button: Support -->
      <button data-action="metamask#buyCoffee" class="btn btn-support">
        Support <span data-metamask-target="price" x-text="price"></span> ETH
      </button>
    </div>
  </div>
</div>

app/views/authors/wallet/_profile.html.erb
<div class="max-w-md mx-auto bg-white rounded-lg shadow-lg overflow-hidden md:max-w-2xl">
  <div class="w-full px-2"> 
    <!-- Avatar -->
    <div class="flex justify-center mt-5">
      <img class="rounded-full" width="100" src="https://media.licdn.com/dms/image/D4D03AQH9GhJevfAQFA/profile-displayphoto-shrink_800_800/0/1669894844340?e=1681344000&v=beta&t=NrAg6YAb6j8IMCPg2k4xn6X1t9SoOI0iOW6l9eyNLxU" alt="">
    </div>
    <div class="flex flex-col text-center mt-3 mb-4">
      <span class="text-2xl font-medium">
      <%# Diogo Wernik %>
      <%= @author.name %>
      </span>
      <span class="text-md text-gray-400">@diogowernik</span>
    </div>
    <!-- Bio -->
    <p class="px-16 text-center text-md text-gray-700">
      Founder of <a href="#" class="text-orange-500 font-semibold">@wtr.ee</a> </br> A secure, convenient platform for managing cryptocurrency assets....
    </p>
    <!-- Tags -->
    <div class="px-16 mt-3 text-center text-gray-400 text-sm">
      <span class="tag">#startup</span>
      <span class="tag">#coding</span>
      <span class="tag">#web3</span>
    </div>
    <!-- Social icons -->
    <div class="flex justify-center mt-5 pt-2 space-x-4 align-baseline">
      <a href="" class="p-2 rounded-md text-gray-400 hover:text-black hover:scale-125 duration-300">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 fill-current" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
      </a>
      <a href="" class="p-2 rounded-md text-gray-400 hover:text-black hover:scale-125 duration-300">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 fill-current" viewBox="0 0 24 24"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/></svg>
      </a>
      <a href="" class="p-2 rounded-md text-gray-400 hover:text-black hover:scale-125 duration-300">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 fill-current" viewBox="0 0 24 24"><path d="M0 3v18h24v-18h-24zm21.518 2l-9.518 7.713-9.518-7.713h19.036zm-19.518 14v-11.817l10 8.104 10-8.104v11.817h-20z"/></svg>
      </a>
    </div>
    <!-- Withdraw button -->
    <div class="px-20 mb-5">
      <button 
        hidden 
        class="btn btn-withdraw" 
        data-metamask-target="withdraw"
        data-action="metamask#withdraw"
      >
        Withdraw
      </button>
    </div>
  </div>
</div>

app/views/coffees/_coffee.html.erb
<div id="<%= dom_id coffee %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Author:</strong>
    <%= coffee.profile_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Sender wallet address:</strong>
    <%= coffee.sender_wallet_address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= coffee.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= coffee.amount %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">contract_id:</strong>
    <%= coffee.contract_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Message:</strong>
    <%= coffee.message %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Tx hash:</strong>
    <%= coffee.tx_hash %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this coffee", coffee, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this coffee', edit_coffee_path(coffee), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/coffees/_form.html.erb
<%= form_with(model: coffee, class: "contents") do |form| %>
  <% if coffee.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(coffee.errors.count, "error") %> prohibited this coffee from being saved:</h2>

      <ul>
        <% coffee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :profile_id %>
    <%= form.number_field :profile_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :sender_wallet_address %>
    <%= form.text_field :sender_wallet_address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :contract_id %>
    <%= form.text_field :contract_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :message %>
    <%= form.text_area :message, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :tx_hash %>
    <%= form.text_field :tx_hash, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/coffees/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing coffee</h1>

  <%= render "form", coffee: @coffee %>

  <%= link_to "Show this coffee", @coffee, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to coffees", coffees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/coffees/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Coffees</h1>
    <%= link_to 'New coffee', new_coffee_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="coffees" class="min-w-full">
    <%= render @coffees %>
  </div>
</div>

app/views/coffees/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New coffee</h1>

  <%= render "form", coffee: @coffee %>

  <%= link_to 'Back to coffees', coffees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/coffees/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @coffee %>

    <%= link_to 'Edit this coffee', edit_coffee_path(@coffee), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this coffee', coffee_path(@coffee), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to coffees', coffees_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/_header.html.erb
  <header class="left-0 top-0 z-50 bg-white w-full shadow-md fixed">
    <div class="mx-auto h-[60px] max-w-7xl">
      <div class="flex justify-between items-center h-full border-b border-slate-500/10 px-5">

          <!-- Logo -->
          <div class="flex items-center">
            <%= image_tag "coffee.png", class: "w-[2rem]" %>
            <span class="ml-2 text-xl font-semibold">
            Buymeacoffee
            </span>
          </div>
          <!-- Wallet -->


          <div 
            hidden
            data-metamask-target="wallet"
          >
            <div class="flex items-center">
            <!-- Network Dropdown -->
              <select 
                  data-action="change->metamask#changeNetwork"
                  class="ml-2 mr-4 bg-white px-8 py-1 rounded"
              >
                  <% @networks.each do |networkKey, networkData| %>
                      <option value="<%= networkKey %>"><%= networkData['name'] %></option>
                  <% end %>
              </select>

            
              <%=image_tag "ethereum.png", class: "mr-1 h-5 w5" %>
              <p 
                data-metamask-target="balance"
                class="mr-5 font-semibold text-slate-500"
              >
              </p>
              <p 
                data-metamask-target="address"
                class="mr-5 font-semibold text-slate-500"
              >
              </p>


            </div>
          </div>
        </div>
      </div>
    </header>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= profile.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Slug:</strong>
    <%= profile.slug %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Bio:</strong>
    <%= profile.bio %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Wallet address:</strong>
    <%= profile.wallet_address %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this profile", profile, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this profile', edit_profile_path(profile), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/profiles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing profile</h1>

  <%= render "form", profile: @profile %>

  <%= link_to "Show this profile", @profile, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to profiles", profiles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/profiles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Profiles</h1>
    <%= link_to 'New profile', new_profile_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="profiles" class="min-w-full">
    <%= render @profiles %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New profile</h1>

  <%= render "form", profile: @profile %>

  <%= link_to 'Back to profiles', profiles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/profiles/wallet/_notification.html.erb
<div hidden data-metamask-target="notification" class="absolute top-10 right-5 w-full max-w-xs bg-green-100 border-t-4 border-green-500 text-green-700 rounded-b px-5 py-3 shadow-md">
  <div class="flex items-center">
    <div>
      <p class="type font-bold">Title</p>
      <p class="message text-sm">Sample message</p>
    </div>
  </div>
</div>